# * device

[device.example]
start_radio_conn_event = 1
ll_enc_req_conn_event = 2
hop_interval = 56
channel_map = 0x00000300       # Map of 0x300 -> BLE channels 8-9 -> Frequencies 2.420-2.422 GHz.
more_data_bit = 0
procedure_interleaving = false # Implies to set the desired request before LL_ENC_REQ.
procedure_interleaving_method = "att_read_request"

[device.fast]
start_radio_conn_event = 1
ll_enc_req_conn_event = 3
hop_interval = 15
channel_map = 0x00000300
more_data_bit = 0
procedure_interleaving = false
procedure_interleaving_method = "att_read_request"

[device.slow]
start_radio_conn_event = 6
ll_enc_req_conn_event = 6
hop_interval = 56
channel_map = 0x00000300
more_data_bit = 0
procedure_interleaving = false
procedure_interleaving_method = "att_read_request"

# * radio.extract

[radio.extract.example]
window = 0.1               # Extracted window, automatically compute if nothing specified [s].
offset = 0.0               # Offset applied to extracted window [s].
trg_bp_low = [1e6]         # Low cutoff frequency of the bandpass filter for the trigger signal.
trg_bp_high = [2e6]        # High cutoff frequency of the bandpass filter for the trigger signal.
trg_lp = 1e4               # Cutoff frequency of the lowpass filter for the trigger signal.
trg_peak_prominence = 0.75 # Fractional of the peak prominence search.
accept_snr_min = 4.8

[radio.extract.1_aes_ff_antenna_8msps]
window = 0.00025
offset = -0.00005
trg_bp_low = [2e6]
trg_bp_high = [3e6]
trg_lp = 1e4
trg_peak_prominence = 0.40
accept_snr_min = 4.8

[radio.extract.1_aes]
window = 0.005
offset = 0.000
trg_bp_low = [7.5e6]
trg_bp_high = [11.5e6]
trg_lp = 1e4
trg_peak_prominence = 0.75

[radio.extract.1_aes_weak]
window = 0.005
offset = 0.000
trg_bp_low = [7.5e6]
trg_bp_high = [11.5e6]
trg_lp = 1e4
trg_peak_prominence = 0.40

[radio.extract.100_aes]
window = 0.07
offset = 0.000
trg_bp_low = [4e6]
trg_bp_high = [4.9e6]
trg_lp = 1e3
trg_peak_prominence = 0.75

[radio.extract.300_aes]
window = 0.2
offset = 0.000
trg_bp_low = [4e6]
trg_bp_high = [4.9e6]
trg_lp = 1e3
trg_peak_prominence = 0.75
